

SetRelationshipBetweenGroups(1, `AMBIENT_GANG_HILLBILLY`, GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, `AMBIENT_GANG_BALLAS`, GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, `AMBIENT_GANG_MEXICAN`, GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, `AMBIENT_GANG_FAMILY`, GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, `AMBIENT_GANG_MARABUNTE`, GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, `AMBIENT_GANG_SALVA`, GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, `GANG_1`, GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, `GANG_2`, GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, `GANG_9`, GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, `GANG_10`, GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, `FIREMAN`, GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, `MEDIC`, GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(1, `COP`, GetHashKey('PLAYER'))